version: '3.3'
services:
  aws-glue:
    build: .
    ports:
      - '8888:8888'
      - '4040:4040'
    volumes:
      - 'C:\Users\User\.aws:/root/.aws:rw'
    container_name: glue_jupyter
    image: /home/jupyter/jupyter_start.sh
