default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: database
      user: postgres
      password: dev_pwd
      port: 5432
      dbname: db
      schema: dbt_dev
      threads: 4
prod:
  target: prod
  outputs:
    prod:
      type: postgres
      host: database
      user: postgres
      password: prod_pwd
      port: 5432
      dbname: db
      schema: dbt_prod
      threads: 4